feat: Enable Algolia Autocomplete search bar
freeCodeCamp/news-theme-archive pull request #44
Opened 2019-07-08 15:31 UTC by scissorsneedfoodtoo

This PR should allow for searching the articles on fCC News.

Just a few notes:
- A search page needs to be enabled. Just add the following to `content/settings/routes.yaml` in the Ghost install before restarting Ghost:
```
routes:
  /search/:
    template: search-results
```
- In `assets/css/algolia-search.css`, change `{ hint: false }` to `{ hint: false, debug: true }` so styling the suggestions in the search drop down easier. The default behavior is to close the dropdown whenever click outside the search bar/drop down.
- We might want to add the Algolia flies in `default.hbs` to the fCC CDN.

2019-07-09 11:34 UTC, raisedadead commented on default.hbs
> +    <script src="https://cdnjs.cloudflare.com/ajax/libs/algoliasearch/3.33.0/algoliasearch.min.js"></script>
Let's move these to the cdn.

2019-07-09 11:34 UTC, raisedadead commented on partials/algolia-search.hbs
> +            // CHANGE URL LATER! => https://freecodecamp.org/news/search?query=${result.query}
### 🚨 REMOVE AFTER QA 🚨

2019-07-10 03:14 UTC, scissorsneedfoodtoo commented on default.hbs
> +    <script src="https://cdnjs.cloudflare.com/ajax/libs/algoliasearch/3.33.0/algoliasearch.min.js"></script>
Sure thing, I'll open up a PR to the cdn and update this once it's merged.

2019-07-16 19:30 UTC, raisedadead commented
Let me know when you are able to squash and then rebase this for a QA.

2019-07-25 08:17 UTC, ahmaxed approved these changes

2019-07-25 08:23 UTC, ahmadabdolsaheb commented
@raisedadead Tested locally, LGMT.
it works great on desktop and mobile.
@scissorsneedfoodtoo great work. the load more button works great on the search page.

2019-07-25 09:00 UTC, scissorsneedfoodtoo commented
@ahmadabdolsaheb, thanks for your review, and all your help with deciding what to index and styling the search results page. I'll change the links to point to fCC News now. Then all we need to do before deploying is update `content/settings/routes.yaml` over on Ghost.

2019-07-25 09:01 UTC, raisedadead requested changes

2019-07-25 09:01 UTC, raisedadead commented on partials/algolia-search.hbs
> +            // CHANGE URL LATER! => https://freecodecamp.org/news/search?query=${result.query}
Let get this resolved.

2019-07-25 09:07 UTC, scissorsneedfoodtoo commented
@raisedadead, just switched those links out. Should be good to go now.

2019-07-25 09:09 UTC, raisedadead commented
Perfect, are we able to track the routes in the ghost-config repo, just for sanity?

2019-07-25 09:10 UTC, raisedadead approved these changes

2019-07-25 09:22 UTC, ahmadabdolsaheb commented
for reference this is how I got it setup locally 

routes:
  /rss/:
    template: rss
    content_type: text/xml
  /search/:
    template: search-results

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/

2019-07-25 10:13 UTC, merged