feat: Comments on pages
freeCodeCamp/news-theme-archive pull request #70
Opened 2019-09-27 16:03 UTC by scissorsneedfoodtoo

Re-enable comments on pages without the #Disable comments internal tag, this time using a partial to load the script.

2019-09-27 16:28 UTC, raisedadead requested changes

2019-09-27 16:28 UTC, raisedadead commented on page.hbs
> +            {{^has tag="#Disable Comments"}}
```suggestion
            {{^has tag="#disable-comments"}}
```

2019-09-27 16:28 UTC, raisedadead commented on page.hbs
> +                {{> "social-row"}}
Should we remove the social share? If yes, it should be its own tags.

2019-09-27 16:29 UTC, raisedadead commented on page.hbs
> +            {{^has tag="#Disable Comments"}}
Lets make it non-ambiguous, spaces are confusing.

2019-09-30 05:09 UTC, scissorsneedfoodtoo commented on page.hbs
> +                {{> "social-row"}}
You're right, this should probably be outside the check for tags.

2019-09-30 05:10 UTC, scissorsneedfoodtoo commented on page.hbs
> +            {{^has tag="#Disable Comments"}}
Yes, I agree. This seems to be a limitation with the `tag` helper where it doesn't dasherize the tag's name, at least for internal tags.

To get around this we can make your suggested change and rename the tag to `#disable-comments`.

2019-09-30 05:54 UTC, scissorsneedfoodtoo commented on page.hbs
> +                {{> "social-row"}}
Not sure if we'll enable the social row for all pages, or just the ones with comments. Will remove the `social-row` partial for now.

2019-09-30 09:25 UTC, raisedadead commented
I noticed that we are not allowing the disabling commenting on posts? Is this intended by design?

https://github.com/freeCodeCamp/news-theme/pull/70/files#diff-83352707fdf3b9057fe76c7a38bf9a03R83-R86

If Yes, then you can DRY out these lines:
https://github.com/freeCodeCamp/news-theme/pull/70/files#diff-83352707fdf3b9057fe76c7a38bf9a03R83-R86

https://github.com/freeCodeCamp/news-theme/pull/70/files#diff-671eaab4c5e99e9dad5764c22e05ee1cR40-R43

If No, then you can DRY out the whole thing by keeping everything in the partial.

I think we should have the ability to disable comments on posts.

2019-09-30 12:14 UTC, scissorsneedfoodtoo commented
I was under the impression that we won't allow disabling comments in posts. Would be good to have that feature as an option, though.

I'll move everything into the partial and have the same check in the article.

2019-09-30 13:00 UTC, raisedadead approved these changes
Please test, merge and deploy.

2019-10-01 02:41 UTC, merged